languageCode = 'fr-ca'
title = 'Club Cedille'
theme = 'cedille'
baseURL = 'https://cedille.etsmtl.ca'

# main menu
[menu]
    [[menu.main]]
        identifier = "accueil"
        name = "Accueil"
        url = "/"
        weight = 1 
    [[menu.main]]
        identifier = "equipe"
        name = "À propos"
        url = "/equipe/"
        weight = 2
    [[menu.main]]
        identifier = "projets"    
        name = "Projets"
        url = "/projets/"
        weight = 3
    [[menu.main]]   
        identifier = "partenaires" 
        name = "Partenaires"
        url = "/partenaires/"
        weight = 4
    [[menu.main]]  
        identifier = "contact" 
        name = "Joignez l'équipe"
        url = "/contact/"
        weight = 5

[params]
    titleFollowUs = "Suivez-nous"
    titleContactPage = "Pour nous contacter"
    copyright = "©"
    year = "2022"

    #General Params
    [params.general]
    logoCedille = "images/cedille-logo-orange.png"
    
    #Address Information Params
    [params.address]
    title = "Adresse"
    address = "1219 rue William <br>Montréal (Québec) <br>H3C 1R1 <br>Local D-2020"
    email = "cedille@etsmtl.net"
    phoneNumber = "5143968800p7302"
    phone = "514 396-8800, poste 7302"

    [params.map]
    APIkey="AIzaSyBbdrK23GFc0JJpng1dX8O_FA_kJv8zhOE"
    latitude = "45.49382"
    longitude = "-73.56233"

    ############ Footer section #############
    [params.footer]
    addressTitle = "Adresse:"
    address = "1219 rue William, Montréal QC, H3C 1R1, Local D-2020"
    contactTitle = "Contact:"
    email = "cedille@etsmtl.net"
    allRightsReserved = "2021 Cédille - Tous droits réservés"
    privacyPolicy = "Politique de confidentialité"
    termsOfService = "Conditions de service"

    [[params.footer.menu]]
    name = "Accueil"
    url = "/"
    weight = 1
    [[params.footer.menu]]
    name = "À propos"
    url = "/equipe/"
    weight = 2
    [[params.footer.menu]]
    name = "Nos projets"
    url = "/projets"
    weight = 3
    [[params.footer.menu]]
    name = "Partenaires"
    url = "/partenaires/"
    weight = 4
    [[params.footer.menu]]
    name = "Contact"
    url = "/contact/"
    weight = 5 

    [[params.footer.social]]
    icon = "fab fa-facebook-f"
    url = "https://www.facebook.com/clubcedille"
    weight = 1
    [[params.footer.social]]
    icon = "fab fa-instagram"
    url = "https://www.instagram.com/cedille.etsmtl"
    weight = 2
    [[params.footer.social]]
    icon = "fab fa-github"
    url = "https://github.com/ClubCedille"
    weight = 3
    [[params.footer.social]]
    icon = "fa-brands fa-linkedin"
    url = "https://www.linkedin.com/company/cedille/about/"
    weight = 4


