languageCode = 'fr-ca'
title = 'Club CEDILLE'
theme = 'cedille'
baseURL = 'https://cedille.etsmtl.ca'

# main menu
[menu]
    [[menu.main]]
        identifier = "accueil"
        name = "Accueil"
        url = "/"
        weight = 1
    [[menu.main]]
        identifier = "a-propos"
        name = "À propos"
        url = "/a-propos/"
        weight = 2
    [[menu.main]]
        identifier = "services"
        name = "Services"
        url = "/services/"
        weight = 3
    [[menu.main]]
        identifier = "equipe"
        name = "Équipe"
        url = "/equipe/"
        weight = 4
    [[menu.main]]
        identifier = "projets"
        name = "Projets"
        url = "/projets/"
        weight = 5
    [[menu.main]]
        identifier = "evenements"
        name = "Événements"
        url = "/evenements/"
        weight = 6
    [[menu.main]]
        identifier = "partenaires"
        name = "Partenaires"
        url = "/partenaires/"
        weight = 7
    [[menu.main]]
        identifier = "contact"
        name = "Joignez l'équipe"
        url = "/contact/"
        weight = 8

[params]
    titleFollowUs = "Suivez-nous"
    titleContactPage = "Pour nous contacter"
    copyright = "©"
    year = "2022"

    #General Params
    [params.general]
    logoCedille = "images/cedille-logo-orange.png"

    #Address Information Params
    [params.address]
    title = "Adresse"
    address = "1219 rue William <br>Montréal (Québec) <br>H3C 1R1 <br>Local D-2020"
    email = "cedille@ens.etsmtl.ca"
    phoneNumber = "5143968800p7302"
    phone = "514 396-8800, poste 7302"

    [params.map]
    APIkey="AIzaSyD1aM-ZRRtAGOlk4qQWdLhHQe0qiAZlFRA"
    latitude = "45.49382"
    longitude = "-73.56233"

    [params.form]
    APIkey = "JJ^j6qUYa^t5bCoQ7bfy"
    link = "https://calidum-rotae.prodv2.cedille.club"

    ############ Footer section #############
    [params.footer]
    addressTitle = "Adresse:"
    address = "1219 rue William, Montréal QC, H3C 1R1, Local D-2020"
    contactTitle = "Contact:"
    email = "cedille@ens.etsmtl.ca"
    allRightsReserved = "2025 | Club CEDILLE"
    privacyPolicy = "Politique de confidentialité"
    termsOfService = "Conditions de service"

    [[params.footer.menu]]
    name = "Accueil"
    url = "/"
    weight = 1
    [[params.footer.menu]]
    name = "À propos"
    url = "/a-propos/"
    weight = 2
    [[params.footer.menu]]
    name = "Équipe"
    url = "/equipe/"
    weight = 3
    [[params.footer.menu]]
    name = "Nos projets"
    url = "/projets/"
    weight = 4
    [[params.footer.menu]]
    name = "Partenaires"
    url = "/partenaires/"
    weight = 5
    [[params.footer.menu]]
    name = "Contact"
    url = "/contact/"
    weight = 6

    [[params.footer.social]]
    icon = "fab fa-facebook-f"
    url = "https://www.facebook.com/clubcedille"
    weight = 1
    [[params.footer.social]]
    icon = "fab fa-instagram"
    url = "https://www.instagram.com/cedille.etsmtl"
    weight = 2
    [[params.footer.social]]
    icon = "fab fa-github"
    url = "https://github.com/ClubCedille"
    weight = 3
    [[params.footer.social]]
    icon = "fa-brands fa-linkedin"
    url = "https://www.linkedin.com/company/cedille/about/"
    weight = 4
    [[params.footer.social]]
    icon = "fa-brands fa-discord"
    url = "https://discord.gg/kX4rXRTMR6"
    weight = 5
