languageCode = 'fr-ca'
title = 'Club Cedille'
theme = 'cedille'


# main menu
[menu]
    [[menu.main]]
        identifier = "accueil"
        name = "Accueil"
        url = "/"
        weight = 1 
    [[menu.main]]
        identifier = "equipe"
        name = "Ã‰quipe"
        url = "/equipe/"
        weight = 2
    [[menu.main]]
        identifier = "projets"    
        name = "Projets"
        url = "/projets"
        weight = 3
    [[menu.main]]   
        identifier = "partenaires" 
        name = "Partenaires"
        url = "/partenaires/"
        weight = 4
    [[menu.main]]  
        identifier = "contact" 
        name = "Contact"
        url = "/contact/"
        weight = 5

[params]

    logo = "images/cedille-logo-orange.png"
    github = "https://github.com/ClubCedille"
    facebook = "https://www.facebook.com/clubcedille"
    instagram = "https://www.instagram.com/cedille.etsmtl/"
    linkedin = "https://www.linkedin.com/company/cedille/about/"


